### ISSUE TITLE
npm vulnerabilities 

### ISSUE THREAD

**Issue by ChiKaLiO** [WelingtonMonteiro/mongoose-history-trace#3]
`  Moderate        Prototype Pollution                                           

  Package         mquery                                                        

  Patched in      >=3.2.3                                                       

  Dependency of   mongoose-history-trace                                        

  Path            mongoose-history-trace > mongoose > mquery                    

  More info       https://npmjs.com/advisories/1649                             

  High            Command Injection                                             

  Package         lodash                                                        

  Patched in      >=4.17.21                                                     

  Dependency of   mongoose-history-trace                                        

  Path            mongoose-history-trace > lodash                               

  More info       https://npmjs.com/advisories/1673      `

**Comment by WelingtonMonteiro** [comment]
bumped
