### ISSUE TITLE
fix: Save changes when "from" value is null

### ISSUE THREAD

**Issue by OscarLlamas6** [WelingtonMonteiro/mongoose-history-trace#9]
It is important to be able to save changes to a collection even when the from value is null. Please consider accepting the submitted PR.

https://github.com/WelingtonMonteiro/mongoose-history-trace/pull/8

**Comment by WelingtonMonteiro** [comment]
New pull request created and new version with fix implemented.
Thank you! In the future new features and bugs fixed!
[Pull request ](https://github.com/WelingtonMonteiro/mongoose-history-trace/commit/6d2f9c112ebd3cdf6033b7e68809f50cf5e398a4)
